name: CI

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      OCAML_JUPYTER_LOG: debug
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.11.0
          - 4.12.0
          - 4.13.0
          - 4.14.0~beta1

    steps:
      - uses: actions/checkout@v2

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          cache-prefix: opam-${{ matrix.ocaml-compiler }}-
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            beta: https://github.com/ocaml/ocaml-beta-repository.git

      - name: Install dependencies
        run: |
          opam install . -y --deps-only --with-test
          opam install 'merlin>3.0.0' -y

      - name: Lint for opam files
        run: opam lint *.opam
      - name: Lint for source files
        run: ./git/pre-commit
      - name: Build
        run: opam exec -- dune build
      - name: Unit tests
        run: opam exec -- dune runtest

      ##
      ## Integration tests
      ##

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install Jupyter
        run: pip install jupyter

      - name: Install ocaml-jupyter kernel
        run: opam pin add jupyter . -y

      - name: Install jupyter-archimedes
        run: opam pin add jupyter-archimedes . -y

      - name: Install kernelspec
        run: |
          ./config/ocaml-jupyter-opam-genspec
          jupyter kernelspec install --user --name ocaml-jupyter "$(opam config var share)/jupyter"
          echo '#use "topfind";;' >> ~/.ocamlinit

      - name: Build integration tests
        run: opam exec -- dune build test/integration/runtest.exe
      - name: An integration test for jupyter-notebook
        run: opam exec -- ./_build/default/test/integration/runtest.exe test/integration/suite/jupyter-notebook.ml
      - name: An integration test for ppx
        run: opam exec -- ./_build/default/test/integration/runtest.exe test/integration/suite/ppx.ml
      - name: An integration test for jupyter-archimedes
        run: opam exec -- ./_build/default/test/integration/runtest.exe test/integration/suite/jupyter-archimedes.ml
